[theme]
base = "light"
primaryColor = "#005b96"
backgroundColor = "#e6f0ff"  # bleu tr√®s clair
secondaryBackgroundColor = "#ffffff"
textColor = "#001f33"
font = "sans serif"

[client]
toolbarMode = "minimal"
